// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

// Protobuf Java Version: 3.25.5
package br.edu.ifsuldeminas.mch.sd.protobuf;

public final class PersonProtos {
  private PersonProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface AddressOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sd.Address)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string patio = 1;</code>
     * @return The patio.
     */
    java.lang.String getPatio();
    /**
     * <code>string patio = 1;</code>
     * @return The bytes for patio.
     */
    com.google.protobuf.ByteString
        getPatioBytes();

    /**
     * <code>int32 number = 2;</code>
     * @return The number.
     */
    int getNumber();

    /**
     * <code>string neighborhood = 3;</code>
     * @return The neighborhood.
     */
    java.lang.String getNeighborhood();
    /**
     * <code>string neighborhood = 3;</code>
     * @return The bytes for neighborhood.
     */
    com.google.protobuf.ByteString
        getNeighborhoodBytes();

    /**
     * <code>string zip_code = 4;</code>
     * @return The zipCode.
     */
    java.lang.String getZipCode();
    /**
     * <code>string zip_code = 4;</code>
     * @return The bytes for zipCode.
     */
    com.google.protobuf.ByteString
        getZipCodeBytes();

    /**
     * <code>string city = 5;</code>
     * @return The city.
     */
    java.lang.String getCity();
    /**
     * <code>string city = 5;</code>
     * @return The bytes for city.
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>string state = 6;</code>
     * @return The state.
     */
    java.lang.String getState();
    /**
     * <code>string state = 6;</code>
     * @return The bytes for state.
     */
    com.google.protobuf.ByteString
        getStateBytes();
  }
  /**
   * Protobuf type {@code sd.Address}
   */
  public static final class Address extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sd.Address)
      AddressOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Address.newBuilder() to construct.
    private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Address() {
      patio_ = "";
      neighborhood_ = "";
      zipCode_ = "";
      city_ = "";
      state_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Address();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.internal_static_sd_Address_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.internal_static_sd_Address_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address.class, br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address.Builder.class);
    }

    public static final int PATIO_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object patio_ = "";
    /**
     * <code>string patio = 1;</code>
     * @return The patio.
     */
    @java.lang.Override
    public java.lang.String getPatio() {
      java.lang.Object ref = patio_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        patio_ = s;
        return s;
      }
    }
    /**
     * <code>string patio = 1;</code>
     * @return The bytes for patio.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPatioBytes() {
      java.lang.Object ref = patio_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        patio_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int NUMBER_FIELD_NUMBER = 2;
    private int number_ = 0;
    /**
     * <code>int32 number = 2;</code>
     * @return The number.
     */
    @java.lang.Override
    public int getNumber() {
      return number_;
    }

    public static final int NEIGHBORHOOD_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object neighborhood_ = "";
    /**
     * <code>string neighborhood = 3;</code>
     * @return The neighborhood.
     */
    @java.lang.Override
    public java.lang.String getNeighborhood() {
      java.lang.Object ref = neighborhood_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        neighborhood_ = s;
        return s;
      }
    }
    /**
     * <code>string neighborhood = 3;</code>
     * @return The bytes for neighborhood.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNeighborhoodBytes() {
      java.lang.Object ref = neighborhood_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        neighborhood_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ZIP_CODE_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object zipCode_ = "";
    /**
     * <code>string zip_code = 4;</code>
     * @return The zipCode.
     */
    @java.lang.Override
    public java.lang.String getZipCode() {
      java.lang.Object ref = zipCode_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        zipCode_ = s;
        return s;
      }
    }
    /**
     * <code>string zip_code = 4;</code>
     * @return The bytes for zipCode.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getZipCodeBytes() {
      java.lang.Object ref = zipCode_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        zipCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CITY_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private volatile java.lang.Object city_ = "";
    /**
     * <code>string city = 5;</code>
     * @return The city.
     */
    @java.lang.Override
    public java.lang.String getCity() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        city_ = s;
        return s;
      }
    }
    /**
     * <code>string city = 5;</code>
     * @return The bytes for city.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCityBytes() {
      java.lang.Object ref = city_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATE_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private volatile java.lang.Object state_ = "";
    /**
     * <code>string state = 6;</code>
     * @return The state.
     */
    @java.lang.Override
    public java.lang.String getState() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        state_ = s;
        return s;
      }
    }
    /**
     * <code>string state = 6;</code>
     * @return The bytes for state.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStateBytes() {
      java.lang.Object ref = state_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        state_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(patio_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, patio_);
      }
      if (number_ != 0) {
        output.writeInt32(2, number_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(neighborhood_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, neighborhood_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(zipCode_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, zipCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, city_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(state_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 6, state_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(patio_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, patio_);
      }
      if (number_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, number_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(neighborhood_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, neighborhood_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(zipCode_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, zipCode_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(city_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, city_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(state_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, state_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address)) {
        return super.equals(obj);
      }
      br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address other = (br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address) obj;

      if (!getPatio()
          .equals(other.getPatio())) return false;
      if (getNumber()
          != other.getNumber()) return false;
      if (!getNeighborhood()
          .equals(other.getNeighborhood())) return false;
      if (!getZipCode()
          .equals(other.getZipCode())) return false;
      if (!getCity()
          .equals(other.getCity())) return false;
      if (!getState()
          .equals(other.getState())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + PATIO_FIELD_NUMBER;
      hash = (53 * hash) + getPatio().hashCode();
      hash = (37 * hash) + NUMBER_FIELD_NUMBER;
      hash = (53 * hash) + getNumber();
      hash = (37 * hash) + NEIGHBORHOOD_FIELD_NUMBER;
      hash = (53 * hash) + getNeighborhood().hashCode();
      hash = (37 * hash) + ZIP_CODE_FIELD_NUMBER;
      hash = (53 * hash) + getZipCode().hashCode();
      hash = (37 * hash) + CITY_FIELD_NUMBER;
      hash = (53 * hash) + getCity().hashCode();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + getState().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sd.Address}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sd.Address)
        br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.AddressOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.internal_static_sd_Address_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.internal_static_sd_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address.class, br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address.Builder.class);
      }

      // Construct using br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        patio_ = "";
        number_ = 0;
        neighborhood_ = "";
        zipCode_ = "";
        city_ = "";
        state_ = "";
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.internal_static_sd_Address_descriptor;
      }

      @java.lang.Override
      public br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address getDefaultInstanceForType() {
        return br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address.getDefaultInstance();
      }

      @java.lang.Override
      public br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address build() {
        br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address buildPartial() {
        br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address result = new br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.patio_ = patio_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.number_ = number_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.neighborhood_ = neighborhood_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.zipCode_ = zipCode_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.city_ = city_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.state_ = state_;
        }
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address) {
          return mergeFrom((br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address other) {
        if (other == br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address.getDefaultInstance()) return this;
        if (!other.getPatio().isEmpty()) {
          patio_ = other.patio_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (other.getNumber() != 0) {
          setNumber(other.getNumber());
        }
        if (!other.getNeighborhood().isEmpty()) {
          neighborhood_ = other.neighborhood_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getZipCode().isEmpty()) {
          zipCode_ = other.zipCode_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.getCity().isEmpty()) {
          city_ = other.city_;
          bitField0_ |= 0x00000010;
          onChanged();
        }
        if (!other.getState().isEmpty()) {
          state_ = other.state_;
          bitField0_ |= 0x00000020;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                patio_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 16: {
                number_ = input.readInt32();
                bitField0_ |= 0x00000002;
                break;
              } // case 16
              case 26: {
                neighborhood_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                zipCode_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                city_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000010;
                break;
              } // case 42
              case 50: {
                state_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000020;
                break;
              } // case 50
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object patio_ = "";
      /**
       * <code>string patio = 1;</code>
       * @return The patio.
       */
      public java.lang.String getPatio() {
        java.lang.Object ref = patio_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          patio_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string patio = 1;</code>
       * @return The bytes for patio.
       */
      public com.google.protobuf.ByteString
          getPatioBytes() {
        java.lang.Object ref = patio_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          patio_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string patio = 1;</code>
       * @param value The patio to set.
       * @return This builder for chaining.
       */
      public Builder setPatio(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        patio_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string patio = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearPatio() {
        patio_ = getDefaultInstance().getPatio();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string patio = 1;</code>
       * @param value The bytes for patio to set.
       * @return This builder for chaining.
       */
      public Builder setPatioBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        patio_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private int number_ ;
      /**
       * <code>int32 number = 2;</code>
       * @return The number.
       */
      @java.lang.Override
      public int getNumber() {
        return number_;
      }
      /**
       * <code>int32 number = 2;</code>
       * @param value The number to set.
       * @return This builder for chaining.
       */
      public Builder setNumber(int value) {

        number_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>int32 number = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumber() {
        bitField0_ = (bitField0_ & ~0x00000002);
        number_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object neighborhood_ = "";
      /**
       * <code>string neighborhood = 3;</code>
       * @return The neighborhood.
       */
      public java.lang.String getNeighborhood() {
        java.lang.Object ref = neighborhood_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          neighborhood_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string neighborhood = 3;</code>
       * @return The bytes for neighborhood.
       */
      public com.google.protobuf.ByteString
          getNeighborhoodBytes() {
        java.lang.Object ref = neighborhood_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          neighborhood_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string neighborhood = 3;</code>
       * @param value The neighborhood to set.
       * @return This builder for chaining.
       */
      public Builder setNeighborhood(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        neighborhood_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string neighborhood = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearNeighborhood() {
        neighborhood_ = getDefaultInstance().getNeighborhood();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string neighborhood = 3;</code>
       * @param value The bytes for neighborhood to set.
       * @return This builder for chaining.
       */
      public Builder setNeighborhoodBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        neighborhood_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object zipCode_ = "";
      /**
       * <code>string zip_code = 4;</code>
       * @return The zipCode.
       */
      public java.lang.String getZipCode() {
        java.lang.Object ref = zipCode_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          zipCode_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string zip_code = 4;</code>
       * @return The bytes for zipCode.
       */
      public com.google.protobuf.ByteString
          getZipCodeBytes() {
        java.lang.Object ref = zipCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          zipCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string zip_code = 4;</code>
       * @param value The zipCode to set.
       * @return This builder for chaining.
       */
      public Builder setZipCode(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        zipCode_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string zip_code = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearZipCode() {
        zipCode_ = getDefaultInstance().getZipCode();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string zip_code = 4;</code>
       * @param value The bytes for zipCode to set.
       * @return This builder for chaining.
       */
      public Builder setZipCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        zipCode_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private java.lang.Object city_ = "";
      /**
       * <code>string city = 5;</code>
       * @return The city.
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string city = 5;</code>
       * @return The bytes for city.
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string city = 5;</code>
       * @param value The city to set.
       * @return This builder for chaining.
       */
      public Builder setCity(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        city_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>string city = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCity() {
        city_ = getDefaultInstance().getCity();
        bitField0_ = (bitField0_ & ~0x00000010);
        onChanged();
        return this;
      }
      /**
       * <code>string city = 5;</code>
       * @param value The bytes for city to set.
       * @return This builder for chaining.
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        city_ = value;
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private java.lang.Object state_ = "";
      /**
       * <code>string state = 6;</code>
       * @return The state.
       */
      public java.lang.String getState() {
        java.lang.Object ref = state_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          state_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string state = 6;</code>
       * @return The bytes for state.
       */
      public com.google.protobuf.ByteString
          getStateBytes() {
        java.lang.Object ref = state_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          state_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string state = 6;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        state_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>string state = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        state_ = getDefaultInstance().getState();
        bitField0_ = (bitField0_ & ~0x00000020);
        onChanged();
        return this;
      }
      /**
       * <code>string state = 6;</code>
       * @param value The bytes for state to set.
       * @return This builder for chaining.
       */
      public Builder setStateBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        state_ = value;
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sd.Address)
    }

    // @@protoc_insertion_point(class_scope:sd.Address)
    private static final br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address();
    }

    public static br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Address>
        PARSER = new com.google.protobuf.AbstractParser<Address>() {
      @java.lang.Override
      public Address parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Address> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Address> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PersonOrBuilder extends
      // @@protoc_insertion_point(interface_extends:sd.Person)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string cpf = 2;</code>
     * @return The cpf.
     */
    java.lang.String getCpf();
    /**
     * <code>string cpf = 2;</code>
     * @return The bytes for cpf.
     */
    com.google.protobuf.ByteString
        getCpfBytes();

    /**
     * <pre>
     * Data de nascimento em milissegundos desde 01/01/1970 (epoch)
     * </pre>
     *
     * <code>int64 birth_day = 3;</code>
     * @return The birthDay.
     */
    long getBirthDay();

    /**
     * <code>.sd.Address address = 4;</code>
     * @return Whether the address field is set.
     */
    boolean hasAddress();
    /**
     * <code>.sd.Address address = 4;</code>
     * @return The address.
     */
    br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address getAddress();
    /**
     * <code>.sd.Address address = 4;</code>
     */
    br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.AddressOrBuilder getAddressOrBuilder();
  }
  /**
   * Protobuf type {@code sd.Person}
   */
  public static final class Person extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:sd.Person)
      PersonOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Person.newBuilder() to construct.
    private Person(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Person() {
      name_ = "";
      cpf_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Person();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.internal_static_sd_Person_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.internal_static_sd_Person_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person.class, br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object name_ = "";
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    @java.lang.Override
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CPF_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object cpf_ = "";
    /**
     * <code>string cpf = 2;</code>
     * @return The cpf.
     */
    @java.lang.Override
    public java.lang.String getCpf() {
      java.lang.Object ref = cpf_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cpf_ = s;
        return s;
      }
    }
    /**
     * <code>string cpf = 2;</code>
     * @return The bytes for cpf.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getCpfBytes() {
      java.lang.Object ref = cpf_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cpf_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BIRTH_DAY_FIELD_NUMBER = 3;
    private long birthDay_ = 0L;
    /**
     * <pre>
     * Data de nascimento em milissegundos desde 01/01/1970 (epoch)
     * </pre>
     *
     * <code>int64 birth_day = 3;</code>
     * @return The birthDay.
     */
    @java.lang.Override
    public long getBirthDay() {
      return birthDay_;
    }

    public static final int ADDRESS_FIELD_NUMBER = 4;
    private br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address address_;
    /**
     * <code>.sd.Address address = 4;</code>
     * @return Whether the address field is set.
     */
    @java.lang.Override
    public boolean hasAddress() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.sd.Address address = 4;</code>
     * @return The address.
     */
    @java.lang.Override
    public br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address getAddress() {
      return address_ == null ? br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address.getDefaultInstance() : address_;
    }
    /**
     * <code>.sd.Address address = 4;</code>
     */
    @java.lang.Override
    public br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.AddressOrBuilder getAddressOrBuilder() {
      return address_ == null ? br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address.getDefaultInstance() : address_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cpf_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cpf_);
      }
      if (birthDay_ != 0L) {
        output.writeInt64(3, birthDay_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeMessage(4, getAddress());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(name_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(cpf_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cpf_);
      }
      if (birthDay_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, birthDay_);
      }
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getAddress());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person)) {
        return super.equals(obj);
      }
      br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person other = (br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getCpf()
          .equals(other.getCpf())) return false;
      if (getBirthDay()
          != other.getBirthDay()) return false;
      if (hasAddress() != other.hasAddress()) return false;
      if (hasAddress()) {
        if (!getAddress()
            .equals(other.getAddress())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + CPF_FIELD_NUMBER;
      hash = (53 * hash) + getCpf().hashCode();
      hash = (37 * hash) + BIRTH_DAY_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getBirthDay());
      if (hasAddress()) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddress().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code sd.Person}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:sd.Person)
        br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.PersonOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.internal_static_sd_Person_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.internal_static_sd_Person_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person.class, br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person.Builder.class);
      }

      // Construct using br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getAddressFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        name_ = "";
        cpf_ = "";
        birthDay_ = 0L;
        address_ = null;
        if (addressBuilder_ != null) {
          addressBuilder_.dispose();
          addressBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.internal_static_sd_Person_descriptor;
      }

      @java.lang.Override
      public br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person getDefaultInstanceForType() {
        return br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person.getDefaultInstance();
      }

      @java.lang.Override
      public br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person build() {
        br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person buildPartial() {
        br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person result = new br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.name_ = name_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.cpf_ = cpf_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.birthDay_ = birthDay_;
        }
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.address_ = addressBuilder_ == null
              ? address_
              : addressBuilder_.build();
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person) {
          return mergeFrom((br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person other) {
        if (other == br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getCpf().isEmpty()) {
          cpf_ = other.cpf_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (other.getBirthDay() != 0L) {
          setBirthDay(other.getBirthDay());
        }
        if (other.hasAddress()) {
          mergeAddress(other.getAddress());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                name_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                cpf_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 24: {
                birthDay_ = input.readInt64();
                bitField0_ |= 0x00000004;
                break;
              } // case 24
              case 34: {
                input.readMessage(
                    getAddressFieldBuilder().getBuilder(),
                    extensionRegistry);
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        name_ = getDefaultInstance().getName();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        name_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object cpf_ = "";
      /**
       * <code>string cpf = 2;</code>
       * @return The cpf.
       */
      public java.lang.String getCpf() {
        java.lang.Object ref = cpf_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          cpf_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string cpf = 2;</code>
       * @return The bytes for cpf.
       */
      public com.google.protobuf.ByteString
          getCpfBytes() {
        java.lang.Object ref = cpf_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          cpf_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string cpf = 2;</code>
       * @param value The cpf to set.
       * @return This builder for chaining.
       */
      public Builder setCpf(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        cpf_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string cpf = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCpf() {
        cpf_ = getDefaultInstance().getCpf();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string cpf = 2;</code>
       * @param value The bytes for cpf to set.
       * @return This builder for chaining.
       */
      public Builder setCpfBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        cpf_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private long birthDay_ ;
      /**
       * <pre>
       * Data de nascimento em milissegundos desde 01/01/1970 (epoch)
       * </pre>
       *
       * <code>int64 birth_day = 3;</code>
       * @return The birthDay.
       */
      @java.lang.Override
      public long getBirthDay() {
        return birthDay_;
      }
      /**
       * <pre>
       * Data de nascimento em milissegundos desde 01/01/1970 (epoch)
       * </pre>
       *
       * <code>int64 birth_day = 3;</code>
       * @param value The birthDay to set.
       * @return This builder for chaining.
       */
      public Builder setBirthDay(long value) {

        birthDay_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Data de nascimento em milissegundos desde 01/01/1970 (epoch)
       * </pre>
       *
       * <code>int64 birth_day = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBirthDay() {
        bitField0_ = (bitField0_ & ~0x00000004);
        birthDay_ = 0L;
        onChanged();
        return this;
      }

      private br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address address_;
      private com.google.protobuf.SingleFieldBuilderV3<
          br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address, br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address.Builder, br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.AddressOrBuilder> addressBuilder_;
      /**
       * <code>.sd.Address address = 4;</code>
       * @return Whether the address field is set.
       */
      public boolean hasAddress() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>.sd.Address address = 4;</code>
       * @return The address.
       */
      public br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address getAddress() {
        if (addressBuilder_ == null) {
          return address_ == null ? br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address.getDefaultInstance() : address_;
        } else {
          return addressBuilder_.getMessage();
        }
      }
      /**
       * <code>.sd.Address address = 4;</code>
       */
      public Builder setAddress(br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          address_ = value;
        } else {
          addressBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.sd.Address address = 4;</code>
       */
      public Builder setAddress(
          br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address.Builder builderForValue) {
        if (addressBuilder_ == null) {
          address_ = builderForValue.build();
        } else {
          addressBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>.sd.Address address = 4;</code>
       */
      public Builder mergeAddress(br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address value) {
        if (addressBuilder_ == null) {
          if (((bitField0_ & 0x00000008) != 0) &&
            address_ != null &&
            address_ != br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address.getDefaultInstance()) {
            getAddressBuilder().mergeFrom(value);
          } else {
            address_ = value;
          }
        } else {
          addressBuilder_.mergeFrom(value);
        }
        if (address_ != null) {
          bitField0_ |= 0x00000008;
          onChanged();
        }
        return this;
      }
      /**
       * <code>.sd.Address address = 4;</code>
       */
      public Builder clearAddress() {
        bitField0_ = (bitField0_ & ~0x00000008);
        address_ = null;
        if (addressBuilder_ != null) {
          addressBuilder_.dispose();
          addressBuilder_ = null;
        }
        onChanged();
        return this;
      }
      /**
       * <code>.sd.Address address = 4;</code>
       */
      public br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address.Builder getAddressBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getAddressFieldBuilder().getBuilder();
      }
      /**
       * <code>.sd.Address address = 4;</code>
       */
      public br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.AddressOrBuilder getAddressOrBuilder() {
        if (addressBuilder_ != null) {
          return addressBuilder_.getMessageOrBuilder();
        } else {
          return address_ == null ?
              br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address.getDefaultInstance() : address_;
        }
      }
      /**
       * <code>.sd.Address address = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address, br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address.Builder, br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.AddressOrBuilder> 
          getAddressFieldBuilder() {
        if (addressBuilder_ == null) {
          addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address, br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Address.Builder, br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.AddressOrBuilder>(
                  getAddress(),
                  getParentForChildren(),
                  isClean());
          address_ = null;
        }
        return addressBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:sd.Person)
    }

    // @@protoc_insertion_point(class_scope:sd.Person)
    private static final br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person();
    }

    public static br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Person>
        PARSER = new com.google.protobuf.AbstractParser<Person>() {
      @java.lang.Override
      public Person parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Person> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Person> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public br.edu.ifsuldeminas.mch.sd.protobuf.PersonProtos.Person getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sd_Address_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sd_Address_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_sd_Person_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_sd_Person_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014person.proto\022\002sd\"m\n\007Address\022\r\n\005patio\030\001" +
      " \001(\t\022\016\n\006number\030\002 \001(\005\022\024\n\014neighborhood\030\003 \001" +
      "(\t\022\020\n\010zip_code\030\004 \001(\t\022\014\n\004city\030\005 \001(\t\022\r\n\005st" +
      "ate\030\006 \001(\t\"T\n\006Person\022\014\n\004name\030\001 \001(\t\022\013\n\003cpf" +
      "\030\002 \001(\t\022\021\n\tbirth_day\030\003 \001(\003\022\034\n\007address\030\004 \001" +
      "(\0132\013.sd.AddressB3\n#br.edu.ifsuldeminas.m" +
      "ch.sd.protobufB\014PersonProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_sd_Address_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_sd_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sd_Address_descriptor,
        new java.lang.String[] { "Patio", "Number", "Neighborhood", "ZipCode", "City", "State", });
    internal_static_sd_Person_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_sd_Person_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_sd_Person_descriptor,
        new java.lang.String[] { "Name", "Cpf", "BirthDay", "Address", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
